# Generated by Django 6.0.7 on 2026-08-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
        ('projects', '0002_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='current_status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], max_length=20)),
                ('target', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_channels', to='projects.project')),
            ],
        ),
    ]
