import { Issue, Monitor, Project } from './types';

export const mockProjects: Project[] = [
  {
    id: 1,
    name: 'Production Web App (Next.js)',
    platform: 'Next.js / React',
    api_key: 'sntry_live_9f8a7b6c5d4e3f2a',
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
    issues_count: 5,
    monitors_count: 4,
  },
  {
    id: 2,
    name: 'Backend Microservices (Go)',
    platform: 'Go / Node.js',
    api_key: 'sntry_live_1a2b3c4d5e6f7g8h',
    created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    issues_count: 2,
    monitors_count: 2,
  },
  {
    id: 3,
    name: 'Mobile App (React Native)',
    platform: 'React Native',
    api_key: 'sntry_live_778899aabbccddee',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    issues_count: 0,
    monitors_count: 1,
  },
];

export const mockIssues: Issue[] = [
  {
    id: 1,
    title: "TypeError: Cannot read properties of undefined (reading 'user')",
    type: 'TypeError',
    message: "Cannot read properties of undefined (reading 'user')",
    culprit: 'src/components/UserProfile.tsx:42 in renderHeader',
    fingerprint: 'abc123',
    count: 142,
    users_count: 38,
    status: 'unhandled',
    handled: false,
    environment: 'production',
    last_seen: new Date(Date.now() - 1000 * 60 * 12).toISOString(), // 12 mins ago
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    stack_trace: [
      "TypeError: Cannot read properties of undefined (reading 'user')",
      "  at UserProfile.renderHeader (src/components/UserProfile.tsx:42:15)",
      "  at UserProfile.render (src/components/UserProfile.tsx:68:10)",
      "  at ReactCompositeComponent.performInitialMount (react-dom.js:3711:13)",
      "  at ReactCompositeComponent.mountComponent (react-dom.js:3582:10)",
    ],
  },
  {
    id: 2,
    title: 'ReferenceError: authToken is not defined',
    type: 'ReferenceError',
    message: 'authToken is not defined in global scope during API call',
    culprit: 'src/lib/api/authClient.ts:18 in getAuthorizationHeader',
    fingerprint: 'def456',
    count: 29,
    users_count: 9,
    status: 'unhandled',
    handled: false,
    environment: 'production',
    last_seen: new Date(Date.now() - 3600000 * 3).toISOString(), // 3 hours ago
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    stack_trace: [
      'ReferenceError: authToken is not defined',
      '  at getAuthorizationHeader (src/lib/api/authClient.ts:18:22)',
      '  at fetchWithAuth (src/lib/api/authClient.ts:45:5)',
      '  at async loadDashboardData (src/app/dashboard/page.tsx:12:18)',
    ],
  },
  {
    id: 3,
    title: 'DatabaseConnectionError: Connection pool exhausted (max 20 reached)',
    type: 'DatabaseError',
    message: 'Timeout acquiring connection from pool after 5000ms',
    culprit: 'backend/db/postgres.go:88 in AcquireClient',
    fingerprint: 'db789',
    count: 85,
    users_count: 54,
    status: 'unhandled',
    handled: false,
    environment: 'production',
    last_seen: new Date(Date.now() - 3600000 * 6).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    stack_trace: [
      'DatabaseConnectionError: Connection pool exhausted (max 20 reached)',
      '  at postgres.AcquireClient (backend/db/postgres.go:88)',
      '  at services.ExecuteQuery (backend/services/query.go:34)',
      '  at controllers.HandleGetUser (backend/controllers/user.go:19)',
    ],
  },
  {
    id: 4,
    title: 'NetworkError: Failed to fetch API endpoint /v1/checkout',
    type: 'NetworkError',
    message: 'HTTP 504 Gateway Timeout while fetching payment response',
    culprit: 'src/services/checkout.ts:104 in processPayment',
    fingerprint: 'net101',
    count: 8,
    users_count: 8,
    status: 'resolved',
    handled: true,
    environment: 'staging',
    last_seen: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    stack_trace: [
      'NetworkError: Failed to fetch API endpoint /v1/checkout',
      '  at processPayment (src/services/checkout.ts:104:12)',
      '  at async handleCheckoutClick (src/components/CheckoutButton.tsx:28:5)',
    ],
  },
  {
    id: 5,
    title: 'SyntaxError: Unexpected token < in JSON at position 0',
    type: 'SyntaxError',
    message: 'Failed to parse JSON response from server (returned HTML error page)',
    culprit: 'src/utils/jsonParser.ts:14 in safeJsonParse',
    fingerprint: 'syn202',
    count: 14,
    users_count: 4,
    status: 'ignored',
    handled: true,
    environment: 'development',
    last_seen: new Date(Date.now() - 86400000 * 3).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    stack_trace: [
      'SyntaxError: Unexpected token < in JSON at position 0',
      '  at JSON.parse (<anonymous>)',
      '  at safeJsonParse (src/utils/jsonParser.ts:14:18)',
      '  at fetchSettings (src/services/settings.ts:52:12)',
    ],
  },
];

export const mockMonitors: Monitor[] = [
  {
    id: 1,
    name: 'Main API Health Check',
    url: 'https://api.example.com/v1/health',
    method: 'GET',
    interval_seconds: 60,
    expected_status: 200,
    is_active: true,
    current_status: 'up',
    response_time_ms: 142,
    uptime_percentage: 99.98,
    last_checked: new Date(Date.now() - 1000 * 45).toISOString(), // 45s ago
    status_history: ['up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up'],
  },
  {
    id: 2,
    name: 'Payment Gateway Webhook',
    url: 'https://api.example.com/v1/webhooks/stripe',
    method: 'POST',
    interval_seconds: 120,
    expected_status: 200,
    is_active: true,
    current_status: 'down',
    response_time_ms: 5004,
    uptime_percentage: 94.12,
    last_checked: new Date(Date.now() - 1000 * 90).toISOString(),
    last_error: 'HTTP 504 Gateway Timeout - Gateway took > 5000ms to respond',
    status_history: ['up', 'up', 'up', 'down', 'down', 'down', 'up', 'up', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'],
  },
  {
    id: 3,
    name: 'Marketing Landing Page',
    url: 'https://example.com',
    method: 'GET',
    interval_seconds: 300,
    expected_status: 200,
    is_active: true,
    current_status: 'up',
    response_time_ms: 88,
    uptime_percentage: 100.0,
    last_checked: new Date(Date.now() - 1000 * 180).toISOString(),
    status_history: ['up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up', 'up'],
  },
  {
    id: 4,
    name: 'Staging Environment Auth',
    url: 'https://staging-auth.example.com/oauth/health',
    method: 'HEAD',
    interval_seconds: 120,
    expected_status: 200,
    is_active: false,
    current_status: 'unknown',
    response_time_ms: 0,
    uptime_percentage: 98.50,
    last_checked: new Date(Date.now() - 3600000 * 24).toISOString(),
    status_history: ['unknown', 'unknown', 'unknown', 'unknown', 'unknown', 'unknown', 'unknown', 'unknown'],
  },
];